project:
  type: website
  
website:
  title: "Pierre Casadebaig"
  description: "A visual journal about algorithmic art, mainly designed for pen plotters."
  site-url: art.casadebaig.net	
  navbar:
    background: "dark"
    right:
      - text: "Home"
        href: "index.qmd"
      - text: "Works"
        menu:
        - text: "Portfolio"
          href: "posts/works/portfolio/index.qmd"
        - text: "Published"          
          href: "posts/works/published/index.qmd"
      - text: "Process"
        menu:
        - text: "Series"
          href: "index.qmd#section-process"
        - text: "Systems"
          href: "index.qmd#section-systems"
      - href: "posts/works/statement/index.qmd"
        text: "Research"
      - href: about.qmd
        text: "About"
      - text: " "
      - href: https://github.com/picasa
        icon: github
      - href: https://bsky.app/profile/pcasadebaig.bsky.social
        icon: twitter
      - text: " "
        
  page-footer: 
    center: "Copyright 2020-2025, Pierre Casadebaig. [{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by-sa/4.0/)." 

execute:
  freeze: auto
  
format:
  html:
    mainfont: Noto Sans Display
    css: styles.css
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    highlight-style: github
    fontsize: 100%
    linkcolor: "#859599"
  
