project:
  type: website
  
website:
  title: "Pierre Casadebaig"
  description: "A visual journal about algorithmic art, mainly designed for pen plotters."
  site-url: art.casadebaig.net	
  navbar:
    background: "dark"
    right:
      - href: "index.qmd"
        text: "Home"
      - href: "posts/works/portfolio/index.qmd"
        text: "Portfolio"
      - href: "posts/works/published/index.qmd"
        text: "Works"
      - href: about.qmd
        text: "About"
      - text: " "
      - href: https://github.com/picasa
        icon: github
      - href: https://twitter.com/pircasa
        icon: twitter
      - text: " "
        
  page-footer: 
    center: "Copyright 2020-2024, Pierre Casadebaig. <br> The art is released under a Creative Commons license [{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by-sa/4.0/)." 

execute:
  freeze: auto
  
format:
  html:
    mainfont: Noto Sans Display
    css: styles.css
    theme: 
      dark: [darkly, styles.scss]
      light: [flatly, styles.scss]
    highlight-style: github
    fontsize: 100%
    linkcolor: "#859599"
  
