project:
  type: website
  
website:
  title: "Pierre Casadebaig"
  description: "A visual journal about algorithmic art, mainly designed for pen plotters."
  site-url: https://art.casadebaig.net
  navbar:
    background: "dark"
    title: "Pierre Casadebaig | *algorithmic drawing*"
    right:
      - text: "Home"
        href: "index.qmd"
      - text: "Works"
        href: "posts/works/index.qmd"
      - text: "Research"          
        href: "posts/research/index.qmd"
      - text: "About"
        href: "posts/about/index.qmd"
      - text: " "
      - href: https://github.com/picasa
        icon: github
      - href: https://bsky.app/profile/pcasadebaig.bsky.social
        icon: bluesky
      - href: https://www.instagram.com/pcasadebaig/
        icon: instagram
      - text: " "
        
  page-footer: 
    center: "Copyright 2020-2026, Pierre Casadebaig. Images [{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by-sa/4.0/)" 

execute:
  freeze: auto
  
format:
  html:
    include-in-header: analytics.html
    mainfont: Noto Sans Display
    css: styles.css
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    highlight-style: github
    fontsize: 100%

  
