project:
  type: website

website:
  title: "Paths"
  description: "A visual blog about algorithmic art, mainly designed for pen plotters."
  site-url: art.casadebaig.net	
  navbar:
    background: "dark"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/picasa
      - icon: twitter
        href: https://twitter.com/pircasa
execute:
  freeze: auto
  
format:
  html:
    fontsize: 100%
    linkcolor: "#859599"
    theme: 
      dark: darkly
      light: flatly
    highlight-style: github
    css: styles.css



