---
title: Paths
author: Pierre Casadebaig
date: '2021-09-14'
splash:
  image: ./splash/background.svg
  caption: Paths
  suffix: 'Pierre Casadebaig'
trailer: ""
---

<style>
.splash-caption-tweak {color: white; text-shadow: 0px 0px 15px black}
.splash-caption-suffix {color: white; text-shadow: 0px 0px 15px black}
</style>

> **A visual blog about algorithmic art, mainly designed for pen plotters.**

I am using the [R](https://www.r-project.org/) programming language to write algorithms that generate digital outputs. Rather than printing, I am interested in using a pen-plotter to draw them on paper. While this process enables drawing with enhanced repetition and precision, it limits the range of techniques available (fills or hatching have to be programmed, pen pressure is constant). Somehow, i assume that the constraints imposed by this machine are a nice frame to the flexibility of code.

This site presents mostly digital outputs and some [paper](/gallery/paper) drawings, and documents the ideas underlying the functioning of the algorithms. Most of the code to study and reproduce these outputs is released on [github `r fontawesome::fa_i("github", verify_fa = FALSE)`](https://github.com/picasa/generative_examples). Overall, making visual art is very new to me, in my day job I am a [scientist `r fontawesome::fa_i("orcid", verify_fa = FALSE)`](https://orcid.org/0000-0001-7225-936X) working in plant biology. Feel free to contact me via [email `r fontawesome::fa_i("github", verify_fa = FALSE)`](https://github.com/picasa) or [twitter `r fontawesome::fa_i("twitter", verify_fa = FALSE)`](https://twitter.com/pircasa) for any questions related to this place.

Unless stated otherwise, the art on this site is released under a CC-BY-SA licence [`r fontawesome::fa_i("creative-commons", verify_fa = FALSE)` `r fontawesome::fa_i("creative-commons-by", verify_fa = FALSE)` `r fontawesome::fa_i("creative-commons-sa", verify_fa = FALSE)`](https://creativecommons.org/licenses/by-sa/4.0/): you are free to reuse the work as long as you attribute the original to me, and derivative works must use the same licence. However, you can support me by buying NFTs, currently on the [objkt.com](https://objkt.com/profile/casadebaig/collections) platform. I only release art on the eco-friendly tezos blockchain, with the *tz1S7NKRdKnh5SKuKpQTz3XCvpctF218ewKF* address (casadebaig.tez).


